default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rsb_development

test:
  <<: *default
  database: rsb_test

production:
  <<: *default
  database: rsb_production
